# Generated by Django 4.0.6 on 2022-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
